# Generated by Django 5.2.7 on 2025-10-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
